import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.Dimension;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JFrame;
import javax.swing.JSeparator;
import javax.swing.LayoutStyle.ComponentPlacement;


/**
 * This is the Main Menu graphical interface. It gives the user the option
 * of creating a new customer or searching for an existing customer.
 * 
 * It was created with the Netbeans GUI builder (new JForm) and refactored
 * for readability.  This reduces the development time at the expense of
 * making future modifications difficult.
 *
 *
 * 
 * @author Chris Lowe
 */
public class MainMenu extends JFrame {

    private JButton aboutJButton;
    private JButton createCustomerJButton;
    private JButton jButtonExit;
    private JSeparator jSeparator1;
    private JButton searchCustomerJButton;
    private JLabel titleJLabel;
    private CustomerCollection customerDatabase;
    
    private static final int WIDTH = 450;
    private static final int HEIGHT = 350;

    public MainMenu(CustomerCollection customerDatabase) {
        this.customerDatabase = customerDatabase;
        init();
    }
    
    private void init() {
   
        titleJLabel = new JLabel();
        jSeparator1 = new JSeparator();
        createCustomerJButton = new JButton();
        searchCustomerJButton = new JButton();
        aboutJButton = new JButton();
        jButtonExit = new JButton();

        setSize(WIDTH, HEIGHT);
        setResizable(false);
        
        //Center the JFrame
        Dimension screensize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        int width = screensize.width;
        int height = screensize.height;
        int width_diff = width - WIDTH;
        int height_diff = height - HEIGHT;
        setLocation(width_diff / 2, height_diff / 2);
        
        titleJLabel.setText("<html><font size=+3>Who Needs E-Diapers</font></html>");
       
        createCustomerJButton.setText("Create Customer");
        createCustomerJButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                createCustomerJButtonActionPerformed(evt);
            }
        });

        searchCustomerJButton.setText("Search for Customer");
        searchCustomerJButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                searchCustomerJButtonActionPerformed(evt);
            }
        });

        aboutJButton.setText("About");
        aboutJButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                aboutJButtonActionPerformed(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                exitJButtonActionPerformed(evt);
            }
        });
        
        //Auto generated by the Netbeans GUI builder
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(titleJLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 369, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aboutJButton)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(jButtonExit, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(createCustomerJButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchCustomerJButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleJLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(createCustomerJButton, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchCustomerJButton, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(aboutJButton)
                    .addComponent(jButtonExit))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        

        
    }

    /**
     * 'Create a customer' button action. Sets the current frame invisible and
     * invokes the Create Customer form.
     */
    private void createCustomerJButtonActionPerformed(ActionEvent evt) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateCustomerForm(customerDatabase).setVisible(true);
            }
        });
        
        setVisible(false);
    }

    /**
     * 'Search for customer' button action. Sets the current frame invisible and
     * invokes the Search Customer form.
     */
    private void searchCustomerJButtonActionPerformed(ActionEvent evt) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchCustomerJFrame(customerDatabase);
            }
        });
        
        setVisible(false);
    }
    
    /**
     * 'About' button action. Invokes the About form.
     */
    private void aboutJButtonActionPerformed(ActionEvent evt) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpJFrame().setVisible(true);
            }
        });
    }
    
    /**
     * 'Exit' button action. Prompts the user to exit the application.
     * 
     * [UPDATE] If the user decides the exit, it will save the database before exiting.
     * [UPDATE] I removed this functionality, it will be saved after every change instead.
     */
    private void exitJButtonActionPerformed(ActionEvent evt) {
        String exitMessage = "Are you sure you want to quit?";
        JOptionPane errorDialog = new JOptionPane();
        
        if (JOptionPane.showConfirmDialog(errorDialog, exitMessage) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        
    }

}
